-- Catalog seed, generated by scripts/import_catalog.py.
-- Source: Weekly Stock Check Records.xlsx
--
-- Re-running is safe: every statement upserts on the workbook's own id,
-- so a second import updates rows rather than duplicating them. Columns
-- the workbook cannot answer are left null and are not overwritten here.

-- Items
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpuc771xt0jo', '100% Rapeseed Oil', 'ingredient', 'L', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpuhgjfoxsvf', 'Aji-no Moto MSG', 'ingredient', 'kg', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpucf3ruuoa9', 'Apple Juice', 'ingredient', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv2moh60h4k', 'Ariake Tonkotsu Paste', 'ingredient', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpucqr4q51x5', 'Balsamic Vinegar', 'ingredient', 'kg', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpuzg1idxdpk', 'Blended Sesame Oil', 'ingredient', 'L', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv49dty4hdf', 'Carrots', 'ingredient', 'kg', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv4uvjvdk38', 'Chicken Carcass', 'ingredient', 'kg', 'freezer', 'freezer', 1)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv4x5mait4u', 'Chicken Feet', 'ingredient', 'Units', 'freezer', 'freezer', 1)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('trace:chicken-fillet', 'Chicken Fillet', 'ingredient', 'kg', 'chill', 'chill', 1)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv4ep7cxb5t', 'Chicken Powder', 'ingredient', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv4w2k806ce', 'Chicken Wings', 'ingredient', 'Units', 'freezer', 'freezer', 1)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv46rcpaytv', 'Chinese Leaves', 'ingredient', 'Units', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpucrpe8rlh5', 'Cider Vinegar', 'ingredient', 'L', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpucspup5soi', 'Cracked Black Pepper', 'ingredient', 'kg', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpxzs2w0ltja', 'Curry Laksa Paste', 'ingredient', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpuzhbhus7w8', 'Dark Soy Sauce', 'ingredient', 'L', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv3vzatkfqx', 'Diced Onions', 'ingredient', 'kg', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv2kmqueish', 'Dried Bird Eye Chillies', 'ingredient', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv4ya5ookoo', 'Femur Bones', 'ingredient', 'kg', 'freezer', 'freezer', 1)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpuct8qvh4np', 'Fine Salt', 'ingredient', 'kg', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv41h7l50xw', 'Ginger Root', 'ingredient', 'kg', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpucubc5jfmh', 'Granulated Sugar', 'ingredient', 'kg', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpuzmv42k3qt', 'Ground Bean Sauce', 'ingredient', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpucv3qqzv8r', 'Ground White Pepper', 'ingredient', 'kg', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpuzklcwj9wl', 'Haepyo Gochujang', 'ingredient', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv4zal7ks2g', 'Hind Feet', 'ingredient', 'kg', 'freezer', 'freezer', 1)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpuzoq8ebfnm', 'Hoi Sin Sauce 20kg', 'ingredient', 'kg', 'ambient', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpuzrf5htyrc', 'Hoi Sin Sauce Cans', 'ingredient', 'Units', 'ambient', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv2v85ihjwb', 'JA Yuzu Seasoning', 'ingredient', 'kg', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpudo60gpapk', 'Japanese Soy Sauce', 'ingredient', 'L', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv2xn3jyhta', 'Korean Hot Pepper Powder', 'ingredient', 'kg', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpuzxj9jnk33', 'Mae Ploy Green Curry Paste', 'ingredient', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpuztdxmggmq', 'Mae Ploy Red Curry Paste', 'ingredient', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpuzytgt4umm', 'Mae Ploy Tom Yum Paste', 'ingredient', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv34d94nwrv', 'Maggi Seasoning', 'ingredient', 'kg', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv4dmq37alr', 'Medium Eggs', 'ingredient', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpuh5g71a757', 'Mirin Style Seasoning', 'ingredient', 'L', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpudkxf1b97v', 'Paprika Sweet', 'ingredient', 'kg', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv3t4jmh10w', 'Peeled Garlic', 'ingredient', 'kg', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv40knt0qpi', 'Peeled Potatoes', 'ingredient', 'kg', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('trace:pork-belly', 'Pork Belly', 'ingredient', 'kg', 'chill', 'chill', 1)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv5107jwcxi', 'Pork Fat', 'ingredient', 'kg', 'freezer', 'freezer', 1)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv2hhfz4f61', 'Rajah Whole Red Chillies', 'ingredient', 'kg', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv2lln2mcfh', 'Red Bean Curd', 'ingredient', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv42tb8kk7i', 'Red Chillies', 'ingredient', 'kg', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpuh883tfymc', 'Rice Vinegar', 'ingredient', 'L', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpuhckliqwi7', 'Shimaya Konbudashi', 'ingredient', 'kg', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv2qb0p8fnl', 'Shio G', 'ingredient', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv2thqzwsy1', 'Shio Paitan', 'ingredient', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv081l4itu1', 'Sichuan Toban Chilli Sauce', 'ingredient', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv2zxrmbswt', 'Spicy Bean Sauce (Mapo)', 'ingredient', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv43vqscfkx', 'Spinach', 'ingredient', 'Units', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv452gsu2ll', 'Spring Onion', 'ingredient', 'Units', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv4frxnle13', 'Sriracha Chilli Sauce', 'ingredient', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpudm0lkbvi8', 'Syrup', 'ingredient', 'kg', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv3bqob8hyp', 'Tahini', 'ingredient', 'kg', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv0637u6fag', 'Toban Djan Chilli Bean Sauce', 'ingredient', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv4gpc6mcvn', 'Tomato Ketchup', 'ingredient', 'kg', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpv4j0ic2j14', 'Tomato Puree Paste', 'ingredient', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpuhe0qrp0fd', 'White Miso', 'ingredient', 'kg', 'ambient', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('ms4h8bkmsw2l', 'White Truffle Oil', 'ingredient', 'kg', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpuhhy0yrbs7', 'Yakisoba Sauce', 'ingredient', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpuzjice0yy4', 'Yutaka Gochujang', 'ingredient', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpwqnttivfp9', 'BBQ Seasoning', 'product', 'Units', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpwp0iaq5eol', 'Beef Tataki', 'product', 'Units', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('msx19517161apq', 'Black Garlic Tonkotsu (Soup)', 'product', 'Units', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpwqoafdxpka', 'Chicken Broth', 'product', 'Units', 'freezer', 'freezer', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpwokfhqje42', 'Chicken Paste', 'product', 'Units', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('msx197b0svuci1', 'Chicken Ramen (Soup)', 'product', 'Units', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpwqcudx7vkq', 'Chilli Oil', 'product', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpylom0aijw5', 'Frozen Ramen : Black Garlic', 'product', 'Units', 'freezer', 'freezer', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpylq1xtnwoq', 'Frozen Ramen : Chicken Tori Paitan', 'product', 'Units', 'freezer', 'freezer', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpylp7salypk', 'Frozen Ramen : Hell Ramen', 'product', 'Units', 'freezer', 'freezer', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpylqnqkh9k0', 'Frozen Ramen : Laksa Ramen', 'product', 'Units', 'freezer', 'freezer', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpwqjdw1mzjc', 'Garlic Oil', 'product', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpwqlw405avb', 'Green Curry Sauce', 'product', 'Units', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpwqnkqbuyiw', 'Green Oil', 'product', 'Units', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('msx196i5t9lvzj', 'Hell Ramen (Soup)', 'product', 'Units', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpwoga5uqxpp', 'Hell Sauce', 'product', 'Units', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpybhcrx14qt', 'Ikigai Chicken Broth', 'product', 'Units', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpwo883223am', 'Kimchi Sauce', 'product', 'Units', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpwp47uz9ugz', 'Laksa Paste', 'product', 'Units', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('msx197xjx312in', 'Laksa Ramen (Soup)', 'product', 'Units', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpwqa03mcg0g', 'Soba Sauce', 'product', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpvbwhnirxon', 'Spicy Miso', 'product', 'Units', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpwqh1089j2e', 'Spicy Teriyaki', 'product', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpwp3fcg6zvj', 'Tantan Sauce', 'product', 'Units', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpwq61oizabz', 'Teriyaki Sauce', 'product', 'Units', 'ambient', 'ambient', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpwqlj8blcjs', 'Tom Yum Tare', 'product', 'Units', 'chill', 'chill', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');
INSERT INTO items (id, name, kind, base_unit, storage_unopened, storage_opened, needs_health_mark)
VALUES ('mpwqpwl8j1px', 'Tonkotsu Broth', 'product', 'Units', 'freezer', 'freezer', NULL)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  base_unit = excluded.base_unit,
  storage_unopened = COALESCE(excluded.storage_unopened, items.storage_unopened),
  storage_opened = COALESCE(excluded.storage_opened, items.storage_opened),
  needs_health_mark = COALESCE(excluded.needs_health_mark, items.needs_health_mark),
  updated_at = datetime('now');

-- Unit conversions
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv4uvjvdk38:case:kg', 'mpv4uvjvdk38', 'case', 'kg', 8.0, '8 kg per case, from catalog-overrides.json (Dean, 2026-08-31)')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv4ya5ookoo:case:kg', 'mpv4ya5ookoo', 'case', 'kg', 10.0, '10 kg per case, from catalog-overrides.json (Dean, 2026-08-31)')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv4zal7ks2g:case:kg', 'mpv4zal7ks2g', 'case', 'kg', 10.0, '10 kg per case, from catalog-overrides.json (Dean, 2026-08-31)')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv5107jwcxi:case:kg', 'mpv5107jwcxi', 'case', 'kg', 10.0, '10 kg per case, from catalog-overrides.json (Dean, 2026-08-31)')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv2hhfz4f61:case:item', 'mpv2hhfz4f61', 'case', 'item', 5.0, '5 items per case, from catalog-overrides.json (Dean, 2026-08-31)')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv2hhfz4f61:item:kg', 'mpv2hhfz4f61', 'item', 'kg', 0.2, '200 g per item, from catalog-overrides.json (Dean, 2026-08-31)')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('trace:chicken-fillet:case:item', 'trace:chicken-fillet', 'case', 'item', 2.0, '2 items per case, from catalog-overrides.json (Dean, 2026-08-31)')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('trace:chicken-fillet:item:kg', 'trace:chicken-fillet', 'item', 'kg', 2.5, '2500 g per item, from catalog-overrides.json (Dean, 2026-08-31)')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuc771xt0jo:case:item', 'mpuc771xt0jo', 'case', 'item', 1.0, '1 items per case, from the workbook''s Items per Case and case size ''1 x 20000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuc771xt0jo:item:L', 'mpuc771xt0jo', 'item', 'L', 20.0, '20000 ml per item, from the workbook''s Items per Case and case size ''1 x 20000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpucf3ruuoa9:case:item', 'mpucf3ruuoa9', 'case', 'item', 12.0, '12 items per case, from the workbook''s Items per Case and case size ''12 x 1000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpucf3ruuoa9:item:Units', 'mpucf3ruuoa9', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpucqr4q51x5:case:item', 'mpucqr4q51x5', 'case', 'item', 12.0, '12 items per case, from the workbook''s Items per Case and case size ''12 x 500''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpucqr4q51x5:item:kg', 'mpucqr4q51x5', 'item', 'kg', 0.5, '500 g per item, from the workbook''s Items per Case and case size ''12 x 500''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpucrpe8rlh5:case:item', 'mpucrpe8rlh5', 'case', 'item', 4.0, '4 items per case, from the workbook''s Items per Case and case size ''4 x 5000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpucrpe8rlh5:item:L', 'mpucrpe8rlh5', 'item', 'L', 5.0, '5000 ml per item, from the workbook''s Items per Case and case size ''4 x 5000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpucspup5soi:case:item', 'mpucspup5soi', 'case', 'item', 6.0, '6 items per case, from the workbook''s Items per Case and case size ''6 x 500''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpucspup5soi:item:kg', 'mpucspup5soi', 'item', 'kg', 0.5, '500 g per item, from the workbook''s Items per Case and case size ''6 x 500''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuct8qvh4np:case:item', 'mpuct8qvh4np', 'case', 'item', 1.0, '1 items per case, from the workbook''s Items per Case and case size ''1 x 25000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuct8qvh4np:item:kg', 'mpuct8qvh4np', 'item', 'kg', 25.0, '25000 g per item, from the workbook''s Items per Case and case size ''1 x 25000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpucubc5jfmh:case:item', 'mpucubc5jfmh', 'case', 'item', 15.0, '15 items per case, from the workbook''s Items per Case and case size ''15 x 1000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpucubc5jfmh:item:kg', 'mpucubc5jfmh', 'item', 'kg', 1.0, '1000 g per item, from the workbook''s Items per Case and case size ''15 x 1000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpucv3qqzv8r:case:item', 'mpucv3qqzv8r', 'case', 'item', 6.0, '6 items per case, from the workbook''s Items per Case and case size ''6 x 600''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpucv3qqzv8r:item:kg', 'mpucv3qqzv8r', 'item', 'kg', 0.6, '600 g per item, from the workbook''s Items per Case and case size ''6 x 600''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpudkxf1b97v:case:item', 'mpudkxf1b97v', 'case', 'item', 6.0, '6 items per case, from the workbook''s Items per Case and case size ''6 x 550''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpudkxf1b97v:item:kg', 'mpudkxf1b97v', 'item', 'kg', 0.55, '550 g per item, from the workbook''s Items per Case and case size ''6 x 550''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpudm0lkbvi8:case:item', 'mpudm0lkbvi8', 'case', 'item', 2.0, '2 items per case, from the workbook''s Items per Case and case size ''2 x 7257''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpudm0lkbvi8:item:kg', 'mpudm0lkbvi8', 'item', 'kg', 7.257, '7257 g per item, from the workbook''s Items per Case and case size ''2 x 7257''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpudo60gpapk:case:item', 'mpudo60gpapk', 'case', 'item', 1.0, '1 items per case, from the workbook''s Items per Case and case size ''1 x 20000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpudo60gpapk:item:L', 'mpudo60gpapk', 'item', 'L', 20.0, '20000 ml per item, from the workbook''s Items per Case and case size ''1 x 20000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuh5g71a757:case:item', 'mpuh5g71a757', 'case', 'item', 1.0, '1 items per case, from the workbook''s Items per Case and case size ''1 x 18000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuh5g71a757:item:L', 'mpuh5g71a757', 'item', 'L', 18.0, '18000 ml per item, from the workbook''s Items per Case and case size ''1 x 18000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuh883tfymc:case:item', 'mpuh883tfymc', 'case', 'item', 1.0, '1 items per case, from the workbook''s Items per Case and case size ''1 x 20000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuh883tfymc:item:L', 'mpuh883tfymc', 'item', 'L', 20.0, '20000 ml per item, from the workbook''s Items per Case and case size ''1 x 20000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuhckliqwi7:case:item', 'mpuhckliqwi7', 'case', 'item', 10.0, '10 items per case, from the workbook''s Items per Case and case size ''1 x 1000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuhckliqwi7:item:kg', 'mpuhckliqwi7', 'item', 'kg', 1.0, '1000 g per item, from the workbook''s Items per Case and case size ''1 x 1000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuhe0qrp0fd:case:item', 'mpuhe0qrp0fd', 'case', 'item', 1.0, '1 items per case, from the workbook''s Items per Case and case size ''1 x 20000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuhe0qrp0fd:item:kg', 'mpuhe0qrp0fd', 'item', 'kg', 20.0, '20000 g per item, from the workbook''s Items per Case and case size ''1 x 20000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuhhy0yrbs7:case:item', 'mpuhhy0yrbs7', 'case', 'item', 6.0, '6 items per case, from the workbook''s Items per Case and case size ''6 x 1795''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuhhy0yrbs7:item:Units', 'mpuhhy0yrbs7', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuhgjfoxsvf:case:item', 'mpuhgjfoxsvf', 'case', 'item', 1.0, '1 items per case, from the workbook''s Items per Case and case size ''1 x 22700''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuhgjfoxsvf:item:kg', 'mpuhgjfoxsvf', 'item', 'kg', 22.7, '22700 g per item, from the workbook''s Items per Case and case size ''1 x 22700''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuzg1idxdpk:case:item', 'mpuzg1idxdpk', 'case', 'item', 6.0, '6 items per case, from the workbook''s Items per Case and case size ''6 x 1800''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuzg1idxdpk:item:L', 'mpuzg1idxdpk', 'item', 'L', 1.8, '1800 ml per item, from the workbook''s Items per Case and case size ''6 x 1800''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuzhbhus7w8:case:item', 'mpuzhbhus7w8', 'case', 'item', 1.0, '1 items per case, from the workbook''s Items per Case and case size ''1 x 8000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuzhbhus7w8:item:L', 'mpuzhbhus7w8', 'item', 'L', 8.0, '8000 ml per item, from the workbook''s Items per Case and case size ''1 x 8000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuzklcwj9wl:case:item', 'mpuzklcwj9wl', 'case', 'item', 20.0, '20 items per case, from the workbook''s Items per Case and case size ''20 x 500''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuzklcwj9wl:item:Units', 'mpuzklcwj9wl', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuzjice0yy4:case:item', 'mpuzjice0yy4', 'case', 'item', 16.0, '16 items per case, from the workbook''s Items per Case and case size ''16 x 500''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuzjice0yy4:item:Units', 'mpuzjice0yy4', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuzmv42k3qt:case:item', 'mpuzmv42k3qt', 'case', 'item', 24.0, '24 items per case, from the workbook''s Items per Case and case size ''1 x 454''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuzmv42k3qt:item:Units', 'mpuzmv42k3qt', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuzoq8ebfnm:case:item', 'mpuzoq8ebfnm', 'case', 'item', 1.0, '1 items per case, from the workbook''s Items per Case and case size ''1 x 20000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuzoq8ebfnm:item:kg', 'mpuzoq8ebfnm', 'item', 'kg', 20.0, '20000 g per item, from the workbook''s Items per Case and case size ''1 x 20000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuztdxmggmq:case:item', 'mpuztdxmggmq', 'case', 'item', 12.0, '12 items per case, from the workbook''s Items per Case and case size ''1 x 1000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuztdxmggmq:item:Units', 'mpuztdxmggmq', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv2kmqueish:case:item', 'mpv2kmqueish', 'case', 'item', 10.0, '10 items per case, from the workbook''s Items per Case and case size ''10 x 1000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv2kmqueish:item:Units', 'mpv2kmqueish', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv2lln2mcfh:case:item', 'mpv2lln2mcfh', 'case', 'item', 48.0, '48 items per case, from the workbook''s Items per Case and case size ''1 x 397''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv2lln2mcfh:item:Units', 'mpv2lln2mcfh', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv0637u6fag:case:item', 'mpv0637u6fag', 'case', 'item', 12.0, '12 items per case, from the workbook''s Items per Case and case size ''1 x 368''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv0637u6fag:item:Units', 'mpv0637u6fag', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv2moh60h4k:case:item', 'mpv2moh60h4k', 'case', 'item', 10.0, '10 items per case, from the workbook''s Items per Case and case size ''10 x 1000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv2moh60h4k:item:Units', 'mpv2moh60h4k', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpxzs2w0ltja:case:item', 'mpxzs2w0ltja', 'case', 'item', 6.0, '6 items per case, from the workbook''s Items per Case and case size ''1 x 1000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpxzs2w0ltja:item:Units', 'mpxzs2w0ltja', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv2qb0p8fnl:case:item', 'mpv2qb0p8fnl', 'case', 'item', 10.0, '10 items per case, from the workbook''s Items per Case and case size ''1 x 1000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv2qb0p8fnl:item:Units', 'mpv2qb0p8fnl', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv2thqzwsy1:case:item', 'mpv2thqzwsy1', 'case', 'item', 10.0, '10 items per case, from the workbook''s Items per Case and case size ''1 x 1000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv2thqzwsy1:item:Units', 'mpv2thqzwsy1', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv2v85ihjwb:case:item', 'mpv2v85ihjwb', 'case', 'item', 6.0, '6 items per case, from the workbook''s Items per Case and case size ''6 x 1800''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv2v85ihjwb:item:kg', 'mpv2v85ihjwb', 'item', 'kg', 1.8, '1800 g per item, from the workbook''s Items per Case and case size ''6 x 1800''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuzxj9jnk33:case:item', 'mpuzxj9jnk33', 'case', 'item', 24.0, '24 items per case, from the workbook''s Items per Case and case size ''24 x 400''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuzxj9jnk33:item:Units', 'mpuzxj9jnk33', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuzytgt4umm:case:item', 'mpuzytgt4umm', 'case', 'item', 12.0, '12 items per case, from the workbook''s Items per Case and case size ''12 x 1000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpuzytgt4umm:item:Units', 'mpuzytgt4umm', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv3bqob8hyp:case:item', 'mpv3bqob8hyp', 'case', 'item', 1.0, '1 items per case, from the workbook''s Items per Case and case size ''1 x 15000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv3bqob8hyp:item:kg', 'mpv3bqob8hyp', 'item', 'kg', 15.0, '15000 g per item, from the workbook''s Items per Case and case size ''1 x 15000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv49dty4hdf:case:item', 'mpv49dty4hdf', 'case', 'item', 1.0, '1 items per case, from the workbook''s Items per Case and case size ''1 x 1000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv49dty4hdf:item:kg', 'mpv49dty4hdf', 'item', 'kg', 1.0, '1000 g per item, from the workbook''s Items per Case and case size ''1 x 1000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv46rcpaytv:case:item', 'mpv46rcpaytv', 'case', 'item', 1.0, '1 items per case, from the workbook''s Items per Case and case size ''1 x 1''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv46rcpaytv:item:Units', 'mpv46rcpaytv', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv3t4jmh10w:case:item', 'mpv3t4jmh10w', 'case', 'item', 10.0, '10 items per case, from the workbook''s Items per Case and case size ''1 x 1000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv3t4jmh10w:item:kg', 'mpv3t4jmh10w', 'item', 'kg', 1.0, '1000 g per item, from the workbook''s Items per Case and case size ''1 x 1000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv3vzatkfqx:case:item', 'mpv3vzatkfqx', 'case', 'item', 1.0, '1 items per case, from the workbook''s Items per Case and case size ''1 x 2000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv3vzatkfqx:item:kg', 'mpv3vzatkfqx', 'item', 'kg', 2.0, '2000 g per item, from the workbook''s Items per Case and case size ''1 x 2000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv40knt0qpi:case:item', 'mpv40knt0qpi', 'case', 'item', 1.0, '1 items per case, from the workbook''s Items per Case and case size ''1 x 5000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv40knt0qpi:item:kg', 'mpv40knt0qpi', 'item', 'kg', 5.0, '5000 g per item, from the workbook''s Items per Case and case size ''1 x 5000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv42tb8kk7i:case:item', 'mpv42tb8kk7i', 'case', 'item', 1.0, '1 items per case, from the workbook''s Items per Case and case size ''1 x 1000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv42tb8kk7i:item:kg', 'mpv42tb8kk7i', 'item', 'kg', 1.0, '1000 g per item, from the workbook''s Items per Case and case size ''1 x 1000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv41h7l50xw:case:item', 'mpv41h7l50xw', 'case', 'item', 1.0, '1 items per case, from the workbook''s Items per Case and case size ''1 x 1000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv41h7l50xw:item:kg', 'mpv41h7l50xw', 'item', 'kg', 1.0, '1000 g per item, from the workbook''s Items per Case and case size ''1 x 1000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv43vqscfkx:case:item', 'mpv43vqscfkx', 'case', 'item', 1.0, '1 items per case, from the workbook''s Items per Case and case size ''1 x 1''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv43vqscfkx:item:Units', 'mpv43vqscfkx', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv452gsu2ll:case:item', 'mpv452gsu2ll', 'case', 'item', 12.0, '12 items per case, from the workbook''s Items per Case and case size ''12 x 1''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv452gsu2ll:item:Units', 'mpv452gsu2ll', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv4dmq37alr:case:item', 'mpv4dmq37alr', 'case', 'item', 180.0, '180 items per case, from the workbook''s Items per Case and case size ''180 x 1''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv4dmq37alr:item:Units', 'mpv4dmq37alr', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv4x5mait4u:case:item', 'mpv4x5mait4u', 'case', 'item', 5.0, '5 items per case, from the workbook''s Items per Case and case size ''5 x 2000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv4x5mait4u:item:Units', 'mpv4x5mait4u', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv4w2k806ce:case:item', 'mpv4w2k806ce', 'case', 'item', 1.0, '1 items per case, from the workbook''s Items per Case and case size ''1 x 10000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv4w2k806ce:item:Units', 'mpv4w2k806ce', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv4ep7cxb5t:case:item', 'mpv4ep7cxb5t', 'case', 'item', 3.0, '3 items per case, from the workbook''s Items per Case and case size ''3 x 1000''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv4ep7cxb5t:item:Units', 'mpv4ep7cxb5t', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv4frxnle13:case:item', 'mpv4frxnle13', 'case', 'item', 12.0, '12 items per case, from the workbook''s Items per Case and case size ''12 x 430''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv4frxnle13:item:Units', 'mpv4frxnle13', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv4gpc6mcvn:case:item', 'mpv4gpc6mcvn', 'case', 'item', 2.0, '2 items per case, from the workbook''s Items per Case and case size ''2 x 4500''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv4gpc6mcvn:item:kg', 'mpv4gpc6mcvn', 'item', 'kg', 4.5, '4500 g per item, from the workbook''s Items per Case and case size ''2 x 4500''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv4j0ic2j14:case:item', 'mpv4j0ic2j14', 'case', 'item', 12.0, '12 items per case, from the workbook''s Items per Case and case size ''12 x 800''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv4j0ic2j14:item:Units', 'mpv4j0ic2j14', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv34d94nwrv:case:item', 'mpv34d94nwrv', 'case', 'item', 6.0, '6 items per case, from the workbook''s Items per Case and case size ''6 x 800''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv34d94nwrv:item:kg', 'mpv34d94nwrv', 'item', 'kg', 0.8, '800 g per item, from the workbook''s Items per Case and case size ''6 x 800''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv081l4itu1:case:item', 'mpv081l4itu1', 'case', 'item', 12.0, '12 items per case, from the workbook''s Items per Case and case size ''12 x 350''')
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');
INSERT INTO unit_conversions (id, item_id, from_unit, to_unit, factor, note)
VALUES ('mpv081l4itu1:item:Units', 'mpv081l4itu1', 'item', 'Units', 1.0, NULL)
ON CONFLICT (id) DO UPDATE SET
  factor = excluded.factor,
  note = excluded.note,
  updated_at = datetime('now');

-- Locations
INSERT INTO locations (id, name, kind)
VALUES ('trace:dry-store', 'Dry Store', 'ambient')
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  updated_at = datetime('now');
INSERT INTO locations (id, name, kind)
VALUES ('trace:dry-store-allergen-free', 'Dry Store Allergen Free Shelf', 'ambient')
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  updated_at = datetime('now');
INSERT INTO locations (id, name, kind)
VALUES ('trace:walk-in-fridge', 'Walk In Fridge', 'chill')
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  updated_at = datetime('now');
INSERT INTO locations (id, name, kind)
VALUES ('trace:walk-in-freezer', 'Walk In Freezer', 'freezer')
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  kind = excluded.kind,
  updated_at = datetime('now');

-- Staff
INSERT INTO staff (id, name)
VALUES ('trace:nikin', 'Nikin')
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  updated_at = datetime('now');
INSERT INTO staff (id, name)
VALUES ('trace:nilesh', 'Nilesh')
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  updated_at = datetime('now');
INSERT INTO staff (id, name)
VALUES ('trace:surendra', 'Surendra')
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  updated_at = datetime('now');
INSERT INTO staff (id, name)
VALUES ('trace:mateus', 'Mateus')
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  updated_at = datetime('now');
INSERT INTO staff (id, name)
VALUES ('trace:paulo', 'Paulo')
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  updated_at = datetime('now');
INSERT INTO staff (id, name)
VALUES ('trace:siku', 'Siku')
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  updated_at = datetime('now');
INSERT INTO staff (id, name)
VALUES ('trace:rogerio', 'Rogerio')
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  updated_at = datetime('now');
INSERT INTO staff (id, name)
VALUES ('trace:aaron', 'Aaron')
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  updated_at = datetime('now');
INSERT INTO staff (id, name)
VALUES ('trace:dean', 'Dean')
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  updated_at = datetime('now');
INSERT INTO staff (id, name)
VALUES ('trace:gunjesh', 'Gunjesh')
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  updated_at = datetime('now');

-- Suppliers
INSERT INTO suppliers (id, name)
VALUES ('trace:lynas', 'Lynas')
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  updated_at = datetime('now');
INSERT INTO suppliers (id, name)
VALUES ('trace:tazaki', 'Tazaki')
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  updated_at = datetime('now');
