-- Generated by scripts/import_customers.py. Do not edit by hand.
-- One row per customer named in the kitchen's dispatch records.
--
-- Seeded 2026-09-04 from the six destinations Dean read off the dispatch
-- records, pending an .xlsx export the importer can run against directly.
-- All six are `dispatched` provenance: a real dispatch note has named each.
-- Lynas is also a supplier; a warehouse the kitchen sends product to is a
-- different fact from a supplier it receives from, and the two tables keep
-- them apart.

INSERT INTO customers (id, name) VALUES ('trace:cust:jfc-warehouse', 'JFC Warehouse') ON CONFLICT (name) DO NOTHING;  -- dispatched
INSERT INTO customers (id, name) VALUES ('trace:cust:lynas-warehouse', 'Lynas Warehouse') ON CONFLICT (name) DO NOTHING;  -- dispatched
INSERT INTO customers (id, name) VALUES ('trace:cust:maki-6-bath-street', 'Maki 6 - Bath Street') ON CONFLICT (name) DO NOTHING;  -- dispatched
INSERT INTO customers (id, name) VALUES ('trace:cust:maki-8-renfield', 'Maki 8 - Renfield') ON CONFLICT (name) DO NOTHING;  -- dispatched
INSERT INTO customers (id, name) VALUES ('trace:cust:maki-ramen-shoreditch', 'Maki Ramen Shoreditch') ON CONFLICT (name) DO NOTHING;  -- dispatched
INSERT INTO customers (id, name) VALUES ('trace:cust:matthews-foods', 'Matthews Foods') ON CONFLICT (name) DO NOTHING;  -- dispatched
