#!/usr/bin/env python3
"""Build the customer list for dispatch from the kitchen's own dispatch records.

Dispatch (P4) sends produced lots to a customer, and the customer has to be
picked from a list rather than typed, so an amendment trail names one
canonical row per customer rather than "JFC", "J.F.C." and "JFC Warehouse"
as three. The `customers` table is empty after P0 on purpose — nothing needed
it until now — and this fills it from evidence rather than from memory.

Two sources, kept apart on the record the same way the supplier importer
keeps its two:

  curated     the `Destinations` tab of the dispatch workbook, the list the
              kitchen maintains by hand.
  dispatched  the distinct `Destination` values seen in the `Dispatches` tab,
              i.e. customers a real delivery note has actually named.

A name in either becomes a customer. Where both have it, that is only worth
noting; the row is the same. Names are matched after collapsing case and
whitespace, and nothing is merged more cleverly than that — "JFC" and "JFC
Warehouse" are left as two unless somebody says otherwise, because guessing
they are one is exactly the kind of silent join this project exists to stop.

The id is minted from the name (`trace:cust:<slug>`) because the records
carry no id of their own. Re-running upserts on the name, so a second import
updates rather than duplicating.

Usage:
    python3 scripts/import_customers.py "~/Downloads/Dispatch Records.xlsx" \
        [--out scripts/customers.sql] [--report scripts/customers-report.txt] \
        [--destinations-sheet Destinations] [--dispatches-sheet Dispatches]
"""

import argparse
import collections
import pathlib
import re
import sys

import openpyxl


def normalise(name):
    return " ".join(str(name).split()).strip()


def slug(name):
    return "trace:cust:" + re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def sql_str(value):
    return "'" + str(value).replace("'", "''") + "'"


def column_values(sheet, wanted):
    """Every value under the column headed `wanted` (case-insensitive)."""
    rows = sheet.iter_rows(values_only=True)
    header = [normalise(cell).lower() if cell else "" for cell in next(rows)]
    if wanted.lower() not in header:
        return []
    at = header.index(wanted.lower())
    seen = []
    for row in rows:
        if row and len(row) > at and row[at]:
            seen.append(normalise(row[at]))
    return seen


def first_column(sheet):
    out = []
    for row in sheet.iter_rows(values_only=True):
        if row and row[0]:
            out.append(normalise(row[0]))
    # Drop a header cell if the first row looks like one.
    if out and out[0].lower() in {"destination", "customer", "customer name", "name"}:
        out = out[1:]
    return out


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("workbook", help="an .xlsx export of the dispatch records")
    parser.add_argument("--out", default="scripts/customers.sql")
    parser.add_argument("--report", default="scripts/customers-report.txt")
    parser.add_argument("--destinations-sheet", default="Destinations")
    parser.add_argument("--dispatches-sheet", default="Dispatches")
    args = parser.parse_args()

    book = openpyxl.load_workbook(
        pathlib.Path(args.workbook).expanduser(), read_only=True, data_only=True
    )

    curated = []
    if args.destinations_sheet in book.sheetnames:
        curated = first_column(book[args.destinations_sheet])

    dispatched = []
    if args.dispatches_sheet in book.sheetnames:
        dispatched = column_values(book[args.dispatches_sheet], "Destination")

    if not curated and not dispatched:
        sys.exit(
            "found no customers: expected a "
            f"'{args.destinations_sheet}' tab or a 'Destination' column on "
            f"'{args.dispatches_sheet}'"
        )

    # name (canonical spelling) -> set of sources
    support = collections.defaultdict(set)
    dispatch_counts = collections.Counter()
    canonical = {}
    for name in curated:
        canonical.setdefault(normalise(name).lower(), name)
        support[normalise(name).lower()].add("curated")
    for name in dispatched:
        key = normalise(name).lower()
        canonical.setdefault(key, name)
        support[key].add("dispatched")
        dispatch_counts[key] += 1

    rows = []
    for key in sorted(canonical):
        name = canonical[key]
        rows.append((slug(name), name, sorted(support[key])))

    lines = [
        "-- Generated by scripts/import_customers.py. Do not edit by hand.",
        "-- One row per customer named in the kitchen's dispatch records.",
        "",
    ]
    for cust_id, name, sources in rows:
        lines.append(
            f"INSERT INTO customers (id, name) VALUES ({sql_str(cust_id)}, {sql_str(name)}) "
            f"ON CONFLICT (name) DO NOTHING;  -- {', '.join(sources)}"
        )
    sql = "\n".join(lines) + "\n"
    pathlib.Path(args.out).write_text(sql)

    both = [n for _, n, s in rows if len(s) == 2]
    curated_only = [n for _, n, s in rows if s == ["curated"]]
    dispatched_only = [n for _, n, s in rows if s == ["dispatched"]]

    report = [
        f"{len(rows)} customers -> {args.out}",
        "",
        "Load it with:",
        f"    npx wrangler d1 execute trace --local --file {args.out}",
        "",
        f"In both the curated list and the dispatch history ({len(both)})",
        *[f"  - {name}" for name in both],
        "",
        f"Curated list only, no dispatch on record ({len(curated_only)})",
        *[f"  - {name}" for name in curated_only],
        "",
        f"Seen in the dispatch history but not on the curated list ({len(dispatched_only)})",
        *[
            f"  - {name} ({dispatch_counts[name.lower()]} lines)"
            for name in dispatched_only
        ],
        "",
        "Names are matched on case and spacing only. Anything that looks like",
        "the same customer spelled two ways is left as two rows — merging them",
        "is a decision for the kitchen, not a guess for the importer.",
        "",
    ]
    text = "\n".join(report) + "\n"
    pathlib.Path(args.report).write_text(text)
    print(text)


if __name__ == "__main__":
    main()
