-- Which supplier each ingredient comes from.
-- Generated by scripts/import_item_suppliers.py from Goods In Records.xlsx.
-- Do not edit: re-run the importer instead.

INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpuc771xt0jo', 'trace:lynas', 'delivered', '117 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpuhgjfoxsvf', 'trace:tazaki', 'delivered', '23 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpucf3ruuoa9', 'trace:lynas', 'delivered', '17 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv2moh60h4k', 'trace:tazaki', 'delivered', '45 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpucqr4q51x5', 'trace:lynas', 'delivered', '8 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpuzg1idxdpk', 'trace:tazaki', 'delivered', '45 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv4uvjvdk38', 'trace:lynas', 'delivered', '90 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv4x5mait4u', 'trace:lynas', 'delivered', '110 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv4w2k806ce', 'trace:lynas', 'delivered', '19 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpucrpe8rlh5', 'trace:lynas', 'delivered', '24 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpucspup5soi', 'trace:lynas', 'delivered', '64 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpxzs2w0ltja', 'trace:tazaki', 'delivered', '14 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv3vzatkfqx', 'trace:lynas', 'delivered', '181 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv4ya5ookoo', 'trace:lynas', 'delivered', '188 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpuct8qvh4np', 'trace:lynas', 'delivered', '15 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv41h7l50xw', 'trace:lynas', 'delivered', '118 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpucubc5jfmh', 'trace:lynas', 'delivered', '90 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpuzmv42k3qt', 'trace:lynas', 'registered', 'on the kitchen''s maintained supplier list, but never seen in the delivery history')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpuzmv42k3qt', 'trace:tazaki', 'delivered', '19 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpucv3qqzv8r', 'trace:lynas', 'delivered', '11 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpuzklcwj9wl', 'trace:tazaki', 'delivered', '66 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv4zal7ks2g', 'trace:lynas', 'delivered', '176 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpuzoq8ebfnm', 'trace:tazaki', 'delivered', '50 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv2v85ihjwb', 'trace:tazaki', 'registered', 'on the kitchen''s maintained supplier list, but never seen in the delivery history')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpudo60gpapk', 'trace:tazaki', 'delivered', '33 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpudo60gpapk', 'trace:lynas', 'delivered', '2 deliveries in the Goods In Records history')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv2xn3jyhta', 'trace:tazaki', 'delivered', '11 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpuzxj9jnk33', 'trace:tazaki', 'delivered', '6 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpuztdxmggmq', 'trace:tazaki', 'delivered', '43 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpuzytgt4umm', 'trace:tazaki', 'delivered', '12 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv34d94nwrv', 'trace:tazaki', 'registered', 'on the kitchen''s maintained supplier list, but never seen in the delivery history')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpuh5g71a757', 'trace:tazaki', 'delivered', '41 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpuh5g71a757', 'trace:lynas', 'delivered', '4 deliveries in the Goods In Records history')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpudkxf1b97v', 'trace:lynas', 'delivered', '6 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv3t4jmh10w', 'trace:lynas', 'delivered', '135 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv40knt0qpi', 'trace:lynas', 'delivered', '179 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('trace:pork-belly', 'trace:lynas', 'delivered', '21 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv5107jwcxi', 'trace:lynas', 'delivered', '174 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv2hhfz4f61', 'trace:tazaki', 'delivered', '7 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv2lln2mcfh', 'trace:lynas', 'registered', 'on the kitchen''s maintained supplier list, but never seen in the delivery history')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv2lln2mcfh', 'trace:tazaki', 'delivered', '16 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv42tb8kk7i', 'trace:lynas', 'delivered', '33 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpuh883tfymc', 'trace:tazaki', 'delivered', '3 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpuh883tfymc', 'trace:lynas', 'delivered', '1 deliveries in the Goods In Records history')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpuhckliqwi7', 'trace:tazaki', 'delivered', '24 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpuhckliqwi7', 'trace:lynas', 'delivered', '1 deliveries in the Goods In Records history')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv2qb0p8fnl', 'trace:tazaki', 'registered', 'on the kitchen''s maintained supplier list, but never seen in the delivery history')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv2thqzwsy1', 'trace:tazaki', 'delivered', '28 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv081l4itu1', 'trace:tazaki', 'registered', 'on the kitchen''s maintained supplier list, but never seen in the delivery history')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv2zxrmbswt', 'trace:tazaki', 'registered', 'on the kitchen''s maintained supplier list, but never seen in the delivery history')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv43vqscfkx', 'trace:lynas', 'delivered', '1 deliveries in the Goods In Records history')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv452gsu2ll', 'trace:lynas', 'delivered', '29 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpudm0lkbvi8', 'trace:lynas', 'delivered', '55 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv0637u6fag', 'trace:lynas', 'delivered', '13 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpv0637u6fag', 'trace:tazaki', 'delivered', '38 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpuhe0qrp0fd', 'trace:tazaki', 'delivered', '54 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('ms4h8bkmsw2l', 'trace:lynas', 'registered', 'on the kitchen''s maintained supplier list, but never seen in the delivery history')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpuhhy0yrbs7', 'trace:tazaki', 'delivered', '58 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
INSERT INTO item_suppliers (item_id, supplier_id, source, note) VALUES ('mpuzjice0yy4', 'trace:tazaki', 'delivered', '3 deliveries in the Goods In Records history, and on the kitchen''s maintained supplier list')
  ON CONFLICT (item_id, supplier_id) DO UPDATE SET source = excluded.source, note = excluded.note, updated_at = datetime('now');
