-- What each product is made from.
-- Generated by scripts/import_recipes.py from the kitchen's batching system.
-- Do not edit: re-run the importer instead.

INSERT INTO recipes (id, item_id, shelf_life_days, note) VALUES ('recipe:mpwp0iaq5eol', 'mpwp0iaq5eol', 180, '6 months, as the kitchen states it')
  ON CONFLICT (item_id) DO UPDATE SET shelf_life_days = excluded.shelf_life_days, note = excluded.note, updated_at = datetime('now');
DELETE FROM recipe_lines WHERE recipe_id = 'recipe:mpwp0iaq5eol';
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwp0iaq5eol:mpuztdxmggmq', 'recipe:mpwp0iaq5eol', 'mpuztdxmggmq', 6.0, 'kg', 1);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwp0iaq5eol:mpuhe0qrp0fd', 'recipe:mpwp0iaq5eol', 'mpuhe0qrp0fd', 6.0, 'kg', 2);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwp0iaq5eol:mpuhgjfoxsvf', 'recipe:mpwp0iaq5eol', 'mpuhgjfoxsvf', 0.6, 'kg', 3);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwp0iaq5eol:mpuc771xt0jo', 'recipe:mpwp0iaq5eol', 'mpuc771xt0jo', 10.0, 'Litres', 4);
INSERT INTO recipes (id, item_id, shelf_life_days, note) VALUES ('recipe:msx19517161apq', 'msx19517161apq', 180, '6 months, as the kitchen states it')
  ON CONFLICT (item_id) DO UPDATE SET shelf_life_days = excluded.shelf_life_days, note = excluded.note, updated_at = datetime('now');
DELETE FROM recipe_lines WHERE recipe_id = 'recipe:msx19517161apq';
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:msx19517161apq:mpwqpwl8j1px', 'recipe:msx19517161apq', 'mpwqpwl8j1px', 18.0, 'Litres', 1);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:msx19517161apq:mpwqjdw1mzjc', 'recipe:msx19517161apq', 'mpwqjdw1mzjc', 1.5, 'kg', 2);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:msx19517161apq:mpudo60gpapk', 'recipe:msx19517161apq', 'mpudo60gpapk', 1.5, 'kg', 3);
INSERT INTO recipes (id, item_id, shelf_life_days, note) VALUES ('recipe:mpwqoafdxpka', 'mpwqoafdxpka', 360, '12 months, as the kitchen states it')
  ON CONFLICT (item_id) DO UPDATE SET shelf_life_days = excluded.shelf_life_days, note = excluded.note, updated_at = datetime('now');
DELETE FROM recipe_lines WHERE recipe_id = 'recipe:mpwqoafdxpka';
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqoafdxpka:mpv4x5mait4u', 'recipe:mpwqoafdxpka', 'mpv4x5mait4u', 6.0, 'kg', 1);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqoafdxpka:mpv4uvjvdk38', 'recipe:mpwqoafdxpka', 'mpv4uvjvdk38', 30.0, 'kg', 2);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqoafdxpka:mpv4w2k806ce', 'recipe:mpwqoafdxpka', 'mpv4w2k806ce', 12.0, 'kg', 3);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqoafdxpka:mpv3t4jmh10w', 'recipe:mpwqoafdxpka', 'mpv3t4jmh10w', 0.7, 'kg', 4);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqoafdxpka:mpv3vzatkfqx', 'recipe:mpwqoafdxpka', 'mpv3vzatkfqx', 2.9, 'kg', 5);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqoafdxpka:mpv41h7l50xw', 'recipe:mpwqoafdxpka', 'mpv41h7l50xw', 1.0, 'kg', 6);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqoafdxpka:mpucspup5soi', 'recipe:mpwqoafdxpka', 'mpucspup5soi', 0.09, 'kg', 7);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqoafdxpka:mpucv3qqzv8r', 'recipe:mpwqoafdxpka', 'mpucv3qqzv8r', 0.06, 'kg', 8);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqoafdxpka:mpuct8qvh4np', 'recipe:mpwqoafdxpka', 'mpuct8qvh4np', 0.48, 'kg', 9);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqoafdxpka:mpv2thqzwsy1', 'recipe:mpwqoafdxpka', 'mpv2thqzwsy1', 5.0, 'kg', 10);
INSERT INTO recipes (id, item_id, shelf_life_days, note) VALUES ('recipe:mpwokfhqje42', 'mpwokfhqje42', 180, '6 months, as the kitchen states it')
  ON CONFLICT (item_id) DO UPDATE SET shelf_life_days = excluded.shelf_life_days, note = excluded.note, updated_at = datetime('now');
DELETE FROM recipe_lines WHERE recipe_id = 'recipe:mpwokfhqje42';
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwokfhqje42:mpuhe0qrp0fd', 'recipe:mpwokfhqje42', 'mpuhe0qrp0fd', 20.0, 'kg', 1);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwokfhqje42:mpuzklcwj9wl', 'recipe:mpwokfhqje42', 'mpuzklcwj9wl', 8.0, 'kg', 2);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwokfhqje42:mpuhckliqwi7', 'recipe:mpwokfhqje42', 'mpuhckliqwi7', 1.0, 'kg', 3);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwokfhqje42:mpucubc5jfmh', 'recipe:mpwokfhqje42', 'mpucubc5jfmh', 1.0, 'kg', 4);
INSERT INTO recipes (id, item_id, shelf_life_days, note) VALUES ('recipe:msx197b0svuci1', 'msx197b0svuci1', 180, '6 months, as the kitchen states it')
  ON CONFLICT (item_id) DO UPDATE SET shelf_life_days = excluded.shelf_life_days, note = excluded.note, updated_at = datetime('now');
DELETE FROM recipe_lines WHERE recipe_id = 'recipe:msx197b0svuci1';
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:msx197b0svuci1:mpwqoafdxpka', 'recipe:msx197b0svuci1', 'mpwqoafdxpka', 18.0, 'Litres', 1);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:msx197b0svuci1:ms4h8bkmsw2l', 'recipe:msx197b0svuci1', 'ms4h8bkmsw2l', 0.5, 'kg', 2);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:msx197b0svuci1:mpv2qb0p8fnl', 'recipe:msx197b0svuci1', 'mpv2qb0p8fnl', 2.0, 'kg', 3);
INSERT INTO recipes (id, item_id, shelf_life_days, note) VALUES ('recipe:mpwqcudx7vkq', 'mpwqcudx7vkq', 180, '6 months, as the kitchen states it')
  ON CONFLICT (item_id) DO UPDATE SET shelf_life_days = excluded.shelf_life_days, note = excluded.note, updated_at = datetime('now');
DELETE FROM recipe_lines WHERE recipe_id = 'recipe:mpwqcudx7vkq';
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqcudx7vkq:mpv2kmqueish', 'recipe:mpwqcudx7vkq', 'mpv2kmqueish', 2.0, 'kg', 1);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqcudx7vkq:mpuc771xt0jo', 'recipe:mpwqcudx7vkq', 'mpuc771xt0jo', 20.0, 'Litres', 2);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqcudx7vkq:mpucubc5jfmh', 'recipe:mpwqcudx7vkq', 'mpucubc5jfmh', 1.0, 'kg', 3);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqcudx7vkq:mpudkxf1b97v', 'recipe:mpwqcudx7vkq', 'mpudkxf1b97v', 0.5, 'kg', 4);
INSERT INTO recipes (id, item_id, shelf_life_days, note) VALUES ('recipe:mpwqjdw1mzjc', 'mpwqjdw1mzjc', 180, '6 months, as the kitchen states it')
  ON CONFLICT (item_id) DO UPDATE SET shelf_life_days = excluded.shelf_life_days, note = excluded.note, updated_at = datetime('now');
DELETE FROM recipe_lines WHERE recipe_id = 'recipe:mpwqjdw1mzjc';
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqjdw1mzjc:mpv3t4jmh10w', 'recipe:mpwqjdw1mzjc', 'mpv3t4jmh10w', 2.0, 'kg', 1);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqjdw1mzjc:mpuc771xt0jo', 'recipe:mpwqjdw1mzjc', 'mpuc771xt0jo', 9.4, 'Litres', 2);
INSERT INTO recipes (id, item_id, shelf_life_days, note) VALUES ('recipe:msx196i5t9lvzj', 'msx196i5t9lvzj', 180, '6 months, as the kitchen states it')
  ON CONFLICT (item_id) DO UPDATE SET shelf_life_days = excluded.shelf_life_days, note = excluded.note, updated_at = datetime('now');
DELETE FROM recipe_lines WHERE recipe_id = 'recipe:msx196i5t9lvzj';
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:msx196i5t9lvzj:mpwqpwl8j1px', 'recipe:msx196i5t9lvzj', 'mpwqpwl8j1px', 18.0, 'Litres', 1);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:msx196i5t9lvzj:mpwoga5uqxpp', 'recipe:msx196i5t9lvzj', 'mpwoga5uqxpp', 5.0, 'kg', 2);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:msx196i5t9lvzj:mpwqcudx7vkq', 'recipe:msx196i5t9lvzj', 'mpwqcudx7vkq', 1.5, 'kg', 3);
INSERT INTO recipes (id, item_id, shelf_life_days, note) VALUES ('recipe:mpwoga5uqxpp', 'mpwoga5uqxpp', 180, '6 months, as the kitchen states it')
  ON CONFLICT (item_id) DO UPDATE SET shelf_life_days = excluded.shelf_life_days, note = excluded.note, updated_at = datetime('now');
DELETE FROM recipe_lines WHERE recipe_id = 'recipe:mpwoga5uqxpp';
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwoga5uqxpp:mpv2lln2mcfh', 'recipe:mpwoga5uqxpp', 'mpv2lln2mcfh', 1.588, 'kg', 1);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwoga5uqxpp:mpv0637u6fag', 'recipe:mpwoga5uqxpp', 'mpv0637u6fag', 2.944, 'kg', 2);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwoga5uqxpp:mpuzmv42k3qt', 'recipe:mpwoga5uqxpp', 'mpuzmv42k3qt', 3.632, 'kg', 3);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwoga5uqxpp:mpuzoq8ebfnm', 'recipe:mpwoga5uqxpp', 'mpuzoq8ebfnm', 3.632, 'kg', 4);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwoga5uqxpp:mpuzklcwj9wl', 'recipe:mpwoga5uqxpp', 'mpuzklcwj9wl', 16.0, 'kg', 5);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwoga5uqxpp:mpuhe0qrp0fd', 'recipe:mpwoga5uqxpp', 'mpuhe0qrp0fd', 8.0, 'kg', 6);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwoga5uqxpp:mpuhgjfoxsvf', 'recipe:mpwoga5uqxpp', 'mpuhgjfoxsvf', 0.6, 'kg', 7);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwoga5uqxpp:mpuzg1idxdpk', 'recipe:mpwoga5uqxpp', 'mpuzg1idxdpk', 1.6, 'Litres', 8);
INSERT INTO recipes (id, item_id, shelf_life_days, note) VALUES ('recipe:mpwo883223am', 'mpwo883223am', 180, '6 months, as the kitchen states it')
  ON CONFLICT (item_id) DO UPDATE SET shelf_life_days = excluded.shelf_life_days, note = excluded.note, updated_at = datetime('now');
DELETE FROM recipe_lines WHERE recipe_id = 'recipe:mpwo883223am';
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwo883223am:mpv3t4jmh10w', 'recipe:mpwo883223am', 'mpv3t4jmh10w', 1.6, 'kg', 1);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwo883223am:mpv41h7l50xw', 'recipe:mpwo883223am', 'mpv41h7l50xw', 0.4, 'kg', 2);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwo883223am:mpv3vzatkfqx', 'recipe:mpwo883223am', 'mpv3vzatkfqx', 1.8, 'kg', 3);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwo883223am:mpucf3ruuoa9', 'recipe:mpwo883223am', 'mpucf3ruuoa9', 2.0, 'Litres', 4);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwo883223am:mpucrpe8rlh5', 'recipe:mpwo883223am', 'mpucrpe8rlh5', 4.0, 'Litres', 5);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwo883223am:mpuzg1idxdpk', 'recipe:mpwo883223am', 'mpuzg1idxdpk', 1.2, 'Litres', 6);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwo883223am:mpucubc5jfmh', 'recipe:mpwo883223am', 'mpucubc5jfmh', 1.2, 'kg', 7);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwo883223am:mpuhckliqwi7', 'recipe:mpwo883223am', 'mpuhckliqwi7', 0.6, 'kg', 8);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwo883223am:mpuct8qvh4np', 'recipe:mpwo883223am', 'mpuct8qvh4np', 0.6, 'kg', 9);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwo883223am:mpv2xn3jyhta', 'recipe:mpwo883223am', 'mpv2xn3jyhta', 1.0, 'kg', 10);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwo883223am:mpuzjice0yy4', 'recipe:mpwo883223am', 'mpuzjice0yy4', 2.0, 'kg', 11);
INSERT INTO recipes (id, item_id, shelf_life_days, note) VALUES ('recipe:mpwp47uz9ugz', 'mpwp47uz9ugz', 180, '6 months, as the kitchen states it')
  ON CONFLICT (item_id) DO UPDATE SET shelf_life_days = excluded.shelf_life_days, note = excluded.note, updated_at = datetime('now');
DELETE FROM recipe_lines WHERE recipe_id = 'recipe:mpwp47uz9ugz';
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwp47uz9ugz:mpuhe0qrp0fd', 'recipe:mpwp47uz9ugz', 'mpuhe0qrp0fd', 6.0, 'kg', 1);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwp47uz9ugz:mpxzs2w0ltja', 'recipe:mpwp47uz9ugz', 'mpxzs2w0ltja', 12.0, 'kg', 2);
INSERT INTO recipes (id, item_id, shelf_life_days, note) VALUES ('recipe:mpwqa03mcg0g', 'mpwqa03mcg0g', 180, '6 months, as the kitchen states it')
  ON CONFLICT (item_id) DO UPDATE SET shelf_life_days = excluded.shelf_life_days, note = excluded.note, updated_at = datetime('now');
DELETE FROM recipe_lines WHERE recipe_id = 'recipe:mpwqa03mcg0g';
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqa03mcg0g:mpuhhy0yrbs7', 'recipe:mpwqa03mcg0g', 'mpuhhy0yrbs7', 21.5, 'kg', 1);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqa03mcg0g:mpucubc5jfmh', 'recipe:mpwqa03mcg0g', 'mpucubc5jfmh', 4.0, 'kg', 2);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqa03mcg0g:mpuzoq8ebfnm', 'recipe:mpwqa03mcg0g', 'mpuzoq8ebfnm', 9.08, 'kg', 3);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqa03mcg0g:mpuhgjfoxsvf', 'recipe:mpwqa03mcg0g', 'mpuhgjfoxsvf', 0.48, 'kg', 4);
INSERT INTO recipes (id, item_id, shelf_life_days, note) VALUES ('recipe:mpvbwhnirxon', 'mpvbwhnirxon', 180, '6 months, as the kitchen states it')
  ON CONFLICT (item_id) DO UPDATE SET shelf_life_days = excluded.shelf_life_days, note = excluded.note, updated_at = datetime('now');
DELETE FROM recipe_lines WHERE recipe_id = 'recipe:mpvbwhnirxon';
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpvbwhnirxon:mpuhe0qrp0fd', 'recipe:mpvbwhnirxon', 'mpuhe0qrp0fd', 20.0, 'kg', 1);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpvbwhnirxon:mpuzjice0yy4', 'recipe:mpvbwhnirxon', 'mpuzjice0yy4', 3.0, 'kg', 2);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpvbwhnirxon:mpuhckliqwi7', 'recipe:mpvbwhnirxon', 'mpuhckliqwi7', 1.0, 'kg', 3);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpvbwhnirxon:mpuhgjfoxsvf', 'recipe:mpvbwhnirxon', 'mpuhgjfoxsvf', 0.5, 'kg', 4);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpvbwhnirxon:mpucubc5jfmh', 'recipe:mpvbwhnirxon', 'mpucubc5jfmh', 0.5, 'kg', 5);
INSERT INTO recipes (id, item_id, shelf_life_days, note) VALUES ('recipe:mpwqh1089j2e', 'mpwqh1089j2e', 180, '6 months, as the kitchen states it')
  ON CONFLICT (item_id) DO UPDATE SET shelf_life_days = excluded.shelf_life_days, note = excluded.note, updated_at = datetime('now');
DELETE FROM recipe_lines WHERE recipe_id = 'recipe:mpwqh1089j2e';
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqh1089j2e:mpudo60gpapk', 'recipe:mpwqh1089j2e', 'mpudo60gpapk', 6.0, 'Litres', 1);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqh1089j2e:mpuh5g71a757', 'recipe:mpwqh1089j2e', 'mpuh5g71a757', 6.0, 'Litres', 2);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqh1089j2e:mpucubc5jfmh', 'recipe:mpwqh1089j2e', 'mpucubc5jfmh', 10.0, 'kg', 3);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqh1089j2e:mpudm0lkbvi8', 'recipe:mpwqh1089j2e', 'mpudm0lkbvi8', 3.5, 'kg', 4);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqh1089j2e:mpv3t4jmh10w', 'recipe:mpwqh1089j2e', 'mpv3t4jmh10w', 0.6, 'kg', 5);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqh1089j2e:mpv2xn3jyhta', 'recipe:mpwqh1089j2e', 'mpv2xn3jyhta', 0.192, 'kg', 6);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqh1089j2e:mpwqcudx7vkq', 'recipe:mpwqh1089j2e', 'mpwqcudx7vkq', 0.6, 'Litres', 7);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqh1089j2e:mpuzoq8ebfnm', 'recipe:mpwqh1089j2e', 'mpuzoq8ebfnm', 7.264, 'kg', 8);
INSERT INTO recipes (id, item_id, shelf_life_days, note) VALUES ('recipe:mpwp3fcg6zvj', 'mpwp3fcg6zvj', 180, '6 months, as the kitchen states it')
  ON CONFLICT (item_id) DO UPDATE SET shelf_life_days = excluded.shelf_life_days, note = excluded.note, updated_at = datetime('now');
DELETE FROM recipe_lines WHERE recipe_id = 'recipe:mpwp3fcg6zvj';
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwp3fcg6zvj:mpv41h7l50xw', 'recipe:mpwp3fcg6zvj', 'mpv41h7l50xw', 0.8, 'kg', 1);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwp3fcg6zvj:mpv3t4jmh10w', 'recipe:mpwp3fcg6zvj', 'mpv3t4jmh10w', 1.6, 'kg', 2);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwp3fcg6zvj:mpv42tb8kk7i', 'recipe:mpwp3fcg6zvj', 'mpv42tb8kk7i', 1.6, 'kg', 3);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwp3fcg6zvj:mpuhe0qrp0fd', 'recipe:mpwp3fcg6zvj', 'mpuhe0qrp0fd', 2.8, 'kg', 4);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwp3fcg6zvj:mpuzklcwj9wl', 'recipe:mpwp3fcg6zvj', 'mpuzklcwj9wl', 8.0, 'kg', 5);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwp3fcg6zvj:mpv0637u6fag', 'recipe:mpwp3fcg6zvj', 'mpv0637u6fag', 2.944, 'kg', 6);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwp3fcg6zvj:mpv3bqob8hyp', 'recipe:mpwp3fcg6zvj', 'mpv3bqob8hyp', 8.35, 'kg', 7);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwp3fcg6zvj:mpucqr4q51x5', 'recipe:mpwp3fcg6zvj', 'mpucqr4q51x5', 2.5, 'Litres', 8);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwp3fcg6zvj:mpuct8qvh4np', 'recipe:mpwp3fcg6zvj', 'mpuct8qvh4np', 0.9, 'kg', 9);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwp3fcg6zvj:mpucubc5jfmh', 'recipe:mpwp3fcg6zvj', 'mpucubc5jfmh', 0.9, 'kg', 10);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwp3fcg6zvj:mpuhgjfoxsvf', 'recipe:mpwp3fcg6zvj', 'mpuhgjfoxsvf', 0.6, 'kg', 11);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwp3fcg6zvj:mpuhckliqwi7', 'recipe:mpwp3fcg6zvj', 'mpuhckliqwi7', 0.3, 'kg', 12);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwp3fcg6zvj:mpuzg1idxdpk', 'recipe:mpwp3fcg6zvj', 'mpuzg1idxdpk', 1.6, 'Litres', 13);
INSERT INTO recipes (id, item_id, shelf_life_days, note) VALUES ('recipe:mpwq61oizabz', 'mpwq61oizabz', 180, '6 months, as the kitchen states it')
  ON CONFLICT (item_id) DO UPDATE SET shelf_life_days = excluded.shelf_life_days, note = excluded.note, updated_at = datetime('now');
DELETE FROM recipe_lines WHERE recipe_id = 'recipe:mpwq61oizabz';
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwq61oizabz:mpudo60gpapk', 'recipe:mpwq61oizabz', 'mpudo60gpapk', 6.0, 'Litres', 1);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwq61oizabz:mpuh5g71a757', 'recipe:mpwq61oizabz', 'mpuh5g71a757', 6.0, 'Litres', 2);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwq61oizabz:mpucubc5jfmh', 'recipe:mpwq61oizabz', 'mpucubc5jfmh', 10.0, 'kg', 3);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwq61oizabz:mpudm0lkbvi8', 'recipe:mpwq61oizabz', 'mpudm0lkbvi8', 4.0, 'kg', 4);
INSERT INTO recipes (id, item_id, shelf_life_days, note) VALUES ('recipe:mpwqpwl8j1px', 'mpwqpwl8j1px', 360, '12 months, as the kitchen states it')
  ON CONFLICT (item_id) DO UPDATE SET shelf_life_days = excluded.shelf_life_days, note = excluded.note, updated_at = datetime('now');
DELETE FROM recipe_lines WHERE recipe_id = 'recipe:mpwqpwl8j1px';
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqpwl8j1px:mpv4ya5ookoo', 'recipe:mpwqpwl8j1px', 'mpv4ya5ookoo', 20.0, 'kg', 1);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqpwl8j1px:mpv4zal7ks2g', 'recipe:mpwqpwl8j1px', 'mpv4zal7ks2g', 10.0, 'kg', 2);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqpwl8j1px:mpv4x5mait4u', 'recipe:mpwqpwl8j1px', 'mpv4x5mait4u', 5.0, 'kg', 3);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqpwl8j1px:mpv5107jwcxi', 'recipe:mpwqpwl8j1px', 'mpv5107jwcxi', 10.0, 'kg', 4);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqpwl8j1px:mpv3vzatkfqx', 'recipe:mpwqpwl8j1px', 'mpv3vzatkfqx', 2.0, 'kg', 5);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqpwl8j1px:mpv3t4jmh10w', 'recipe:mpwqpwl8j1px', 'mpv3t4jmh10w', 1.0, 'kg', 6);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqpwl8j1px:mpv40knt0qpi', 'recipe:mpwqpwl8j1px', 'mpv40knt0qpi', 5.0, 'kg', 7);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqpwl8j1px:mpucspup5soi', 'recipe:mpwqpwl8j1px', 'mpucspup5soi', 0.192, 'kg', 8);
INSERT INTO recipe_lines (id, recipe_id, item_id, quantity, unit, sort_order) VALUES ('recipe:mpwqpwl8j1px:mpv2moh60h4k', 'recipe:mpwqpwl8j1px', 'mpv2moh60h4k', 6.0, 'kg', 9);
